"""movies_migration

Revision ID: cea060200e18
Revises: 91979b40eb38
Create Date: 2023-08-28 02:51:57.598608-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea060200e18'
down_revision = '91979b40eb38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Numeric(precision=11, scale=1), nullable=True),
    sa.Column('company', sa.String(length=73), nullable=True),
    sa.Column('country', sa.String(length=30), nullable=True),
    sa.Column('director', sa.String(length=32), nullable=True),
    sa.Column('genre', sa.String(length=9), nullable=True),
    sa.Column('gross', sa.Numeric(precision=11, scale=1), nullable=True),
    sa.Column('name', sa.String(length=83), nullable=True),
    sa.Column('rating', sa.String(length=13), nullable=True),
    sa.Column('released', sa.String(length=10), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('star', sa.String(length=27), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('writer', sa.String(length=32), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.drop_column('user', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.alter_column('user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_table('movies')
    # ### end Alembic commands ###
